### ISSUE TITLE
Save Setup should save to the same file that was loaded as a setup

### ISSUE THREAD

**Issue by strk** [sonosaurus/sonobus#173]
Or how else would we keep multiple settings separated ?
See also #172

**Comment by essej** [comment]
Well, the intention behind the setups is that they should be intentionally saved, and not automatically saved... in that you specifically set up a scenario that you want to be able to load in the future (among others). More like fixed presets you would load. Of course you can Save Setup... again and choose the same file to overwrite... but it's always an intentional and manual process. So, are you just asking for a Save Setup, and a Save Setup As... ?

**Comment by strk** [comment]
Save Setup exists already, but always saves to an hardcoded path no matter which setup you loaded. Additionally, automatic save is ALREADY in effect, because as soon as I join or leave a room the file with hardcoded path ( ~/.config/sonobus/SonoBus.settings on my system ) gets updated.

A `Save Setup As` may be useful, in general, but not for my setup, which consists in SonoBus being loaded by a "session manager" with a setup file (passed with --load-setup switch) specific to my session. What I'd like to see happen is that these automatic updates of the setup file were done against THAT file I asked to use, not the hardcoded path.

I agree automatically-saving something should be an opt-in, so maybe there could be a switch to enable or disable it

**Comment by essej** [comment]
Sorry for the misunderstanding, I didn’t mention the automatic state saving which always goes to the specific location, which is currently the only automatic saving that happens. The save setup command I was referring to was the one in the menu. The command line load-setup was again intentionally a read-only location. I would want to add another command line option that would optionally auto-save back to a specified location, because again, not everyone would want to overwrite a preset setup file.

**Comment by strk** [comment]
How is the "save setup" different from "state saving" ? What goes in "state" and what goes in "setup" ? Is `SonoBus.settings` "state" or "setup" ?

**Comment by essej** [comment]
Pretty much everything that goes into the state saving (SonoBus.settings) goes in the saved setup files, just a few application settings don't go into a saved setup. You can take a look at the XML files themselves to see how similar the SonoBus.settings is to a setup file saved with the File menu->Save Setup...

**Comment by strk** [comment]
I'm closing this issue as it became a bit confusing, given the initial misunderstanding. Will file a new ticket.
