### ISSUE TITLE
Stream desktop audio

### ISSUE THREAD

**Issue by VelocityRa** [sonosaurus/sonobus#87]
Can I stream the audio that applications output to my computer (Youtube, Spotify, games, whatever), to other people over the internet with SonoBus?

I assume it's not directly possible, but are there any work arounds perhaps? There's https://github.com/rdp/virtual-audio-capture-grabber-device and a few others but I don't see any of them in the Input section of SonoBus.

**Comment by AtmanActive** [comment]
This is a common problem.
So much so that audio device manufacturers started integrating this functionality into their drivers. 
This feature is called _loopback_. 
Not an easy thing to resolve, especially in ASIO environment.
There are software solutions like Virtual Audio Cable, [VB-Audio Voicemeeter](https://vb-audio.com/Voicemeeter/index.htm) and [Synchronous Audio Router](http://sar.audio/), but which one will work in your particular situation is impossible to tell.
Good luck.

**Comment by VelocityRa** [comment]
Thank you for the info :)
